### ISSUE TITLE
Bad design for printing and building

### ISSUE THREAD

**Issue by EBMare** [LucidVR/lucidgloves-hardware#3]
Nice work, but the design sucks.
I tried multiple times to print the parts but they are always too fragile or not perfectly sized.
edit: It is a pain in the ass to build it and it is impossible to get the spring in place (tried it 10 times and didnt get it right)

**Comment by zwarunek** [comment]
What printer are you using? I had no issues with either printing or building using the Prusa mk3s?

**Comment by EBMare** [comment]
Anycubic i3 mega

Am Di., 13. Apr. 2021 um 18:37 Uhr schrieb zwarunek <
***@***.***>:

**Comment by gaming-se** [comment]
@EBMare wrote:
> Nice work, but the design sucks.
> I tried multiple times to print the parts but they are always too fragile or not perfectly sized.
> edit: It is a pain in the ass to build it and it is impossible to get the spring in place (tried it 10 times and didnt get it right)

There are other ways to make a Issue and you could learn that its common to use more neutral Statements even if u disappointed and had your problems with it, you are not on Amazon or other web shop to make a 1 Star review for a Product that got sold to you, nobody is interested in these in a open source Comunity Hub. give constructive ideas especially if u have experience in 3D Printing and know something better say what could be made better or specifically cause your problems, that wuld give the developers a much better motivation to change it or review it.

Your Issue in neural might have sound like this:
1.  Depending on used Printer it might be good to **build the parts more robust** (Bigger wall thickness on some places) [_u forgot to name the parts @EBMare _] if the layer adhesion of filament is not strong Enough. Downside of these might be that the print over all would be bulkier but might be better for some users.

2.  Knowing the tolerances that where used for this print might help users to decide if they have to change the STL files or resize them [_ u did not mention where things do not fit @EBMare _]

3.  I had problems inserting the spring into this Build (tried it 10 times and didnt get it right),it might be interesting to build an spring insertion tool.


I'm printing the parts right now (maybe I might say more after I'm done)

From my Point of View some of these things that might be interesting for this project:
1. to add a README file inside the STL Files Folder that points to [Parts-Printing-Guide](https://github.com/LucidVR/lucidgloves-hardware/wiki/Parts-Printing-Guide)
2. Inside the [Parts-Printing-Guide](https://github.com/LucidVR/lucidgloves-hardware/wiki/Parts-Printing-Guide) is a "not need supports" and an alignment image. I think that might be not working on printers with not enough fan cooling. You will get a Problem with red marked position in _[Prot3.1 Holder.stl]_ and _[Prot3.1 EasySpool*.stl]_. In my image (Because its not bridging and mid-air-printing or bigger then 60° overhang):

![FDM90DegreeOverhangProblem](https://user-images.githubusercontent.com/82713677/115118281-ee2e0600-9f91-11eb-9b5a-7bf507fa6a10.JPG)

3. It's common to safe the files in orientation they are printed to save others the work to rotate them and think about right alignment. It saves much time if u have to reprint things and just want to drag and drop files.

4.  I think providing a note to users that they might do a calibration test like this might be interesting https://www.thingiverse.com/thing:342198 i have a calibrated printer, so I personally watch at the tolerance only to know if it's a loose fit design

**And one more thing to the developers:**
Thanks for sharing the prototype of this project with everyone and try to make VR gloves affordable. Will be glad to see the progress of it especially haptic feedback.

**Comment by lucas-vrtech** [comment]
As stated, this project is in very early stages and these designs are out for people who are in a rush to give it a try. I'm going to be improving the designs a lot, but you need to be patient :)

Thank you very much for the suggestions @gaming-se , I will take them into consideration. If anyone else has any suggestions on short term improvements to the models, feel free to message me on discord. `LucidVR#0001`.
